build:
  stage: build
  image: maven:3.5.0-jdk-8
  script: 
    - mvn clean install

.maven_central:
  stage: deploy
  image: maven:3.5.0-jdk-8
  script:
    - git checkout $CI_BUILD_REF_NAME
    - git reset --hard origin/$CI_BUILD_REF_NAME
    - git config user.email "oss@ceh.ac.uk"
    - git config user.name "Open Source Software"
    - mkdir /root/.gnupg
    - base64 -d <<< $SECRING_GPG_64 > /root/.gnupg/secring.gpg
    - base64 -d <<< $PUBRING_GPG_64 > /root/.gnupg/pubring.gpg
    - echo "$SETTINGS_XML" > /root/.m2/settings.xml
    - mvn release:prepare release:perform -B -Dusername=$GITLAB_USERNAME -Dpassword=$GITLAB_DEPLOY_TOKEN -Darguments=-Dgpg.passphrase=$GPG_PASS | sed -e "s/$GITLAB_DEPLOY_TOKEN/*******/g"
  when: manual
